"""业务数据访问接口(集中定义,基准 01)。

服务层只依赖本文件 Protocol,实现位于 application/repository;
测试用内存 fake 实现同一协议(基准 03)。
"""

from __future__ import annotations

import uuid
from typing import Protocol

from app.domain.models import AuditLog, Membership, RefreshToken, Space, User


class UserRepository(Protocol):
    def get(self, user_id: uuid.UUID) -> User | None: ...
    def get_by_username(self, username: str) -> User | None: ...
    def create(self, user: User) -> User: ...
    def save(self, user: User) -> User: ...


class RefreshTokenRepository(Protocol):
    def get_by_hash(self, token_hash: str) -> RefreshToken | None: ...
    def create(self, token: RefreshToken) -> RefreshToken: ...
    def delete(self, token: RefreshToken) -> None: ...
    def delete_by_user(self, user_id: uuid.UUID) -> None: ...


class SpaceRepository(Protocol):
    def get(self, space_id: uuid.UUID) -> Space | None: ...
    def create(self, space: Space) -> Space: ...
    def save(self, space: Space) -> Space: ...
    def delete(self, space: Space) -> None: ...
    def list_for_user(self, user_id: uuid.UUID) -> list[tuple[Space, int]]: ...
    def get_membership(self, space_id: uuid.UUID, user_id: uuid.UUID) -> Membership | None: ...
    def get_member(self, space_id: uuid.UUID, member_user_id: uuid.UUID) -> Membership | None: ...
    def list_members(self, space_id: uuid.UUID) -> list[tuple[Membership, User]]: ...
    def add_member(self, membership: Membership) -> Membership: ...
    def update_member(self, membership: Membership) -> Membership: ...
    def remove_member(self, membership: Membership) -> None: ...


class AuditRepository(Protocol):
    def add(self, log: AuditLog) -> AuditLog: ...
    def list_for_space(
        self, space_id: uuid.UUID, limit: int, offset: int
    ) -> tuple[list[AuditLog], int]: ...
